language: php

php:
  - 5.6
services:
  - mysql

before_install:
  #setup database
  - mysql -e 'CREATE DATABASE djland;'
  - cat setup/database_structures/*.sql > setup.sql
  - mysql -u root djland < setup.sql
  #setup laravel api
  - cd app/api2
  - cp .env.sample .env
  - cp phpunit.xml.sample phpunit.xml
  - composer self-update

install:
  - composer install --no-scripts --no-interaction
  - composer install --no-interaction
  - php artisan key:generate

# Cache composer
cache:
  directories:
    - $HOME/.composer/cache


before_script:
  - sudo apt-get update
  - sudo apt-get --yes install apache2 libapache2-mod-fastcgi
  # enable php-fpm
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  #- ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo ls -la ~/.phpenv/versions/$(phpenv version-name)/
  - sudo ls -la
  - cd ../../
  - sudo cp -f build/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart
  - cd app/api2

script:
    #TODO: add coverage and QUnit to travis CI tests
  - vendor/bin/phpunit

notifications:
  email:
    - technicalmanager@citr.ca
