CREATE TABLE `library_edits` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `format_id` tinyint(4) DEFAULT NULL,
  `old_format_id` tinyint(4) DEFAULT NULL,
  `catalog` tinytext,
  `old_catalog` tinytext,
  `cancon` tinyint(1) DEFAULT NULL,
  `old_cancon` tinyint(1) DEFAULT NULL,
  `femcon` tinyint(1) DEFAULT NULL,
  `old_femcon` tinyint(1) DEFAULT NULL,
  `local` int(1) DEFAULT NULL,
  `old_local` int(1) DEFAULT NULL,
  `playlist` tinyint(1) DEFAULT NULL,
  `old_playlist` tinyint(1) DEFAULT NULL,
  `compilation` tinyint(1) DEFAULT NULL,
  `old_compilation` tinyint(1) DEFAULT NULL,
  `digitized` tinyint(1) DEFAULT NULL,
  `old_digitized` tinyint(1) DEFAULT NULL,
  `status` tinytext,
  `old_status` tinytext,
  `artist` tinytext,
  `old_artist` tinytext,
  `title` tinytext,
  `old_title` tinytext,
  `label` tinytext,
  `old_label` tinytext,
  `genre` tinytext,
  `old_genre` tinytext,
  `library_id` int(11) DEFAULT NULL,
  `updated_at` date DEFAULT NULL,
  `created_at` date DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
