CREATE TABLE `submission_songs` (
  `song_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `submission_id` int(10) unsigned DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `album_artist` varchar(255) DEFAULT NULL,
  `album_title` varchar(255) DEFAULT NULL,
  `song_title` varchar(255) DEFAULT NULL,
  `credit` varchar(45) DEFAULT NULL,
  `track_num` smallint(6) DEFAULT '0',
  `tracks_total` smallint(6) DEFAULT '0',
  `genre` varchar(255) DEFAULT NULL,
  `s/t` bit(1) DEFAULT b'0',
  `v/a` bit(1) DEFAULT b'0',
  `compilation` bit(1) DEFAULT b'0',
  `composer` varchar(255) DEFAULT NULL,
  `crtc` tinyint(4) DEFAULT NULL,
  `year` year(4) DEFAULT NULL,
  `length` int(10) unsigned DEFAULT NULL,
  `file_location` mediumtext,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`song_id`),
  KEY `fk_submission_songs_1_idx` (`submission_id`),
  CONSTRAINT `fk_submission_songs_1` FOREIGN KEY (`submission_id`) REFERENCES `submissions` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
