CREATE TABLE `year_rollover` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `membership_year` varchar(16) NOT NULL DEFAULT '2014/2015',
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;
