CREATE TABLE `membership_years` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `member_id` int(11) unsigned NOT NULL,
  `membership_year` varchar(9) NOT NULL,
  `paid` varchar(1) NOT NULL DEFAULT '0',
  `sports` varchar(1) DEFAULT '0',
  `news` varchar(1) DEFAULT '0',
  `arts` varchar(1) DEFAULT '0',
  `music` varchar(1) DEFAULT '0',
  `show_hosting` varchar(1) DEFAULT '0',
  `live_broadcast` varchar(1) DEFAULT '0',
  `tech` varchar(1) DEFAULT '0',
  `programming_committee` varchar(1) DEFAULT '0',
  `ads_psa` varchar(1) DEFAULT '0',
  `promotions_outreach` varchar(1) DEFAULT '0',
  `discorder` varchar(1) DEFAULT '0',
  `discorder_2` varchar(1) DEFAULT '0',
  `digital_library` varchar(1) DEFAULT '0',
  `photography` varchar(1) DEFAULT '0',
  `tabling` varchar(45) DEFAULT '0',
  `dj` varchar(1) DEFAULT '0',
  `other` varchar(45) DEFAULT NULL,
  `create_date` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `edit_date` timestamp NULL DEFAULT NULL,
  `womens_collective` varchar(16) DEFAULT '0',
  `indigenous_collective` varchar(16) DEFAULT '0',
  `accessibility_collective` varchar(16) DEFAULT '0',
  PRIMARY KEY (`id`,`member_id`,`membership_year`),
  KEY `member_id_idx` (`member_id`),
  CONSTRAINT `id` FOREIGN KEY (`member_id`) REFERENCES `membership` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=880 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
