SELECT * FROM `dev.djland`.library_songs;CREATE TABLE `library_songs` (
  `song_id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `library_id` int(11) DEFAULT NULL,
  `artist` varchar(255) DEFAULT NULL,
  `album_artist` varchar(255) DEFAULT NULL,
  `album_title` varchar(255) DEFAULT NULL,
  `song_title` varchar(255) DEFAULT NULL,
  `credit` varchar(45) DEFAULT NULL,
  `track_num` smallint(6) DEFAULT '0',
  `tracks_total` smallint(6) DEFAULT '0',
  `genre` varchar(255) DEFAULT NULL,
  `s/t` bit(1) DEFAULT b'0',
  `v/a` bit(1) DEFAULT b'0',
  `compilation` bit(1) DEFAULT b'0',
  `composer` varchar(255) DEFAULT NULL,
  `crtc` tinyint(4) DEFAULT NULL,
  `year` year(4) DEFAULT NULL,
  `length` int(10) unsigned DEFAULT NULL,
  `file_location` mediumtext,
  `updated_at` datetime NOT NULL,
  `created_at` datetime NOT NULL,
  PRIMARY KEY (`song_id`),
  KEY `fk_library_songs_1_idx` (`library_id`),
  CONSTRAINT `fk_library_songs_1` FOREIGN KEY (`library_id`) REFERENCES `library` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=latin1;
