angular.module('playsheet.constants', []);

var tags = ['playlist', 'cancon', 'femcon', 'instrumental', 'partial', 'hit', 'background', 'theme'];
var help = {
    album: "Enter the title of the album, EP, or single that the track is released on."
        + "If playing an mp3 or streaming from youtube, soundcloud, etc, please take a moment to find the title of the album,"
        + "EP, or single that the track is released on. If it is unreleased, enter 'unreleased'. "
        + "If you are confused about what to enter here, please contact music@citr.ca This will help the artist chart "
        + "and help provide listeners with information about the release."
    , song: "Enter the name of the track"
    , artist: "Enter the name of the artist"
    , comp: "OPTIONAL: Enter the name of the composer or author"
    , timeHelp1: "Hit the CUE button when the song starts playing . Or enter the start time. Time Format is HOUR:MIN"
    , timeHelp2: "Enter the duration of the song. Time Format is MIN:SECOND"
    , playlist: "Playlist (New) Content: Was the song released in the last 6 months? "
    , cancon: "Cancon: two of the following must apply: Music written by a Canadian, Artist performing it is Canadian, Performance takes place in Canada, Lyrics Are written by a Canadian"
    , femcon: "Femcon: two of the following must apply: Music is written by a female, Performers (at least one) are female, Words are written by a female, Recording is made by a female engineer."
    , instrumental: "Is the song instrumental? (no vocals)"
    , partial: "Partial songs: For a track to count as cancon, you need to play the whole thing and it must be at least 1 minute."
    , hit: "Has the song ever been a hit in Canada?  By law, the maximum is 10% Hits played, but we aim for 0% - you really shouldn't play hits!"
    , theme: "Is the song your themesong?"
    , background: "Is the song playing in the background? Talking over the intro to a song does not count as background"
    , crtc: "Category 2: Rock, Pop, Dance, Country, Acoustic, Easy Listening.  Category 3: Concert, Folk, World Beat, Jazz, Blues, Religious, Experimental. (Click me for more info!)"
    , songHelp: "Enter the name of the song"
    , lang: "The language of the song"
    , adsHelp: "Station IDs must be played or spoken in the first ten minutes of every hour"
    , guestsHelp: "Any non-music features on your show.  This helps us to reach our 15% local spoken word minimum"
    , toolsHelp: "Tools: [-]Delete the row  [+]Add a new row below"
    , accessCon: "AccessCon: Applies to artists who are D/deaf, visibly, and/or invisibly disabled"
    , afroCon: "AfroCon: Applies to artists who are Black and may be assigned to an artist who is visibly Black in visuals provided by the artist and/or representation. Any album logged as AfroCon qualifies as POC’Con as well"
    , indigiCon: "IndigiCon: Applies to artists who are Indigenous, Métis, and/or Inuit. Includes all Indigenous peoples who have been displaced and/or affected by colonial occupation on Turtle Island"
    , pocCon: "POCcon: Applies to artists of color and may be assigned to an artist who is racialized and/or visibly non-white in visuals provided by the artist and/or representatives"
    , queerCon: "QueerCon: Applies to artists who are lesbian, gay, bisexual/pansexual, trans, two spirit, queer/questioning, intersex, asexual, and/or any other non-heterosexual, non-cisgender identity"
    , is_local: "Local: Applies to artists from the lower mainland"
}